"""Daily Roast prompt (CLAUDE.md §9.2.1, §7.2).

Generated by the §9.2.1 cron — quarrel-cheap, 280 characters or less,
references one tracked fact, ends with an implied dare. Plain text out
(no JSON envelope) since the push body and the chat bubble both render
the raw string.
"""

DAILY_ROAST_PROMPT = """You are writing a single roast for a user who's signed up for a daily one. They want this. Don't soften.

You will receive:
<context>
  username: their handle
  persona: the §10.1 slug they picked for the roast voice
</context>
<user_facts>
{up to 5 tracked facts about the user — past statements, commitments, identities}
</user_facts>

Write ONE roast.

Rules:
- Under 280 characters TOTAL. Strict cap.
- Reference ONE of the facts specifically — quote or paraphrase it. Not generic gym/career roasts.
- Cutting, witty. Never about identity, body, disability, or unchangeable traits.
- Second person.
- End with an implied dare or unanswered challenge — not a literal "I dare you" but a line that makes them want to prove you wrong.
- No emojis, no preamble, no markdown, no quotes around the output.

Output the roast text only."""
