import Link from "next/link";

// Marketing footer (CLAUDE.md §17). Carries the §50 EU AI Act disclosure
// at the bottom so visitors who scrolled past the hero have seen it
// before signing up.

const LEGAL = [
  { href: "/legal/privacy/en", label: "Privacy" },
  { href: "/legal/terms/en", label: "Terms" },
  { href: "/legal/ai-disclosure/en", label: "AI Disclosure" },
  { href: "/legal/acceptable-use/en", label: "Acceptable Use" },
  { href: "/legal/cookies/en", label: "Cookies" },
  { href: "/legal/dpa/en", label: "DPA" },
] as const;

const SOCIAL = [
  { href: "https://x.com/quarrel_ai", label: "X" },
  { href: "https://github.com/quarrel-ai", label: "GitHub" },
] as const;

export function Footer() {
  return (
    <footer>
      <div className="mx-auto grid max-w-6xl gap-10 px-6 py-16 md:grid-cols-[1.5fr_1fr_1fr_1fr]">
        <div className="flex flex-col gap-3">
          <p className="text-base font-semibold">Quarrel AI</p>
          <p className="max-w-sm text-sm text-muted-foreground">
            The AI that won&apos;t let you lie to yourself.
          </p>
          <p className="text-xs text-muted-foreground">
            Operated from Dhaka, Bangladesh. Web payments by Polar.sh.
          </p>
        </div>

        <nav className="flex flex-col gap-2 text-sm">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Product
          </p>
          <Link href="/pricing" className="hover:underline">
            Pricing
          </Link>
          <Link href="/roast/linkedin" className="hover:underline">
            Roast My X
          </Link>
          <Link href="/personas" className="hover:underline">
            Personas
          </Link>
          <Link href="/login" className="hover:underline">
            Sign in
          </Link>
        </nav>

        <nav className="flex flex-col gap-2 text-sm">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Legal
          </p>
          {LEGAL.map((l) => (
            <Link key={l.href} href={l.href} className="hover:underline">
              {l.label}
            </Link>
          ))}
        </nav>

        <nav className="flex flex-col gap-2 text-sm">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Elsewhere
          </p>
          {SOCIAL.map((l) => (
            <a
              key={l.href}
              href={l.href}
              rel="noreferrer noopener"
              target="_blank"
              className="hover:underline"
            >
              {l.label}
            </a>
          ))}
          <a
            href="https://status.quarrel.ai"
            rel="noreferrer noopener"
            target="_blank"
            className="hover:underline"
          >
            Status
          </a>
        </nav>
      </div>

      <div className="border-t">
        <div className="mx-auto flex max-w-6xl flex-col gap-3 px-6 py-6 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between">
          <p>© {new Date().getFullYear()} Quarrel AI. All rights reserved.</p>
          <p className="max-w-2xl text-muted-foreground/90">
            You are interacting with an AI system. Replies are generated by a
            language model, not written by a human. They can be wrong, biased,
            or contradictory. Not professional advice.
          </p>
        </div>
      </div>
    </footer>
  );
}
