"""Beta-cohort invite sender (CLAUDE.md §27 step 72).

The /signup magic-link signup is the standard path. For the closed
beta we don't gate /signup — we just send hand-picked invitees a
Supabase admin-issued magic link that drops them straight into
onboarding. Insertion into beta_invites is the queue; this service
drains it.

Failure to send marks error_message on the row so a future cron tick
won't blindly retry; an operator clears the field after fixing the
underlying issue (e.g. an invalid address).
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any

import structlog
from supabase import AsyncClient

from app.config import get_settings
from app.services._db_typing import rows as _rows
from app.services.email import send_email
from app.services.supabase_client import get_supabase

log = structlog.get_logger(__name__)


# Magic link generated by Supabase admin lasts 24 hours by default.
LINK_TTL_HOURS = 24


@dataclass(slots=True)
class InviteResult:
    invite_id: str
    email: str
    sent: bool
    error: str | None = None


async def _list_unsent(
    supabase: AsyncClient, *, limit: int
) -> list[dict[str, Any]]:
    res = (
        await supabase.table("beta_invites")
        .select("id, email, cohort_tag, notes")
        .is_("sent_at", "null")
        .is_("error_message", "null")
        .order("created_at", desc=False)
        .limit(limit)
        .execute()
    )
    return _rows(res.data)


async def _generate_signup_link(
    supabase: AsyncClient, *, email: str, redirect_to: str
) -> str | None:
    """Supabase admin magiclink — auto-creates the auth.users row if
    new, otherwise just signs the existing user in. Returns None on
    any failure so the caller can stamp error_message.
    """

    try:
        res = await supabase.auth.admin.generate_link(
            {
                "type": "magiclink",
                "email": email,
                "options": {"redirect_to": redirect_to},
            }
        )
    except Exception as err:  # noqa: BLE001 — best-effort
        log.warning("beta_invites.generate_link_failed", email=email, error=str(err))
        return None

    data = getattr(res, "properties", None) or getattr(res, "data", None)
    if isinstance(data, dict):
        link = data.get("action_link") or data.get("magic_link")
        if isinstance(link, str) and link.startswith("http"):
            return link
    # supabase-py 2.x exposes the link at .properties.action_link
    properties = getattr(getattr(res, "properties", None), "action_link", None)
    if isinstance(properties, str):
        return properties
    log.warning("beta_invites.unparseable_link_response", email=email)
    return None


async def _stamp_sent(
    supabase: AsyncClient, *, invite_id: str
) -> None:
    await (
        supabase.table("beta_invites")
        .update(
            {
                "sent_at": datetime.now(UTC).isoformat(),
                "expires_at": _expires_at(),
            }
        )
        .eq("id", invite_id)
        .execute()
    )


async def _stamp_failed(
    supabase: AsyncClient, *, invite_id: str, message: str
) -> None:
    await (
        supabase.table("beta_invites")
        .update({"error_message": message[:500]})
        .eq("id", invite_id)
        .execute()
    )


def _expires_at() -> str:
    from datetime import timedelta

    return (datetime.now(UTC) + timedelta(hours=LINK_TTL_HOURS)).isoformat()


async def _send_one(
    supabase: AsyncClient,
    *,
    invite: dict[str, Any],
    redirect_to: str,
) -> InviteResult:
    invite_id = str(invite["id"])
    email = str(invite["email"]).strip().lower()

    if not email or "@" not in email:
        await _stamp_failed(supabase, invite_id=invite_id, message="invalid email")
        return InviteResult(invite_id=invite_id, email=email, sent=False, error="invalid_email")

    link = await _generate_signup_link(supabase, email=email, redirect_to=redirect_to)
    if link is None:
        await _stamp_failed(
            supabase, invite_id=invite_id, message="failed to generate magic link"
        )
        return InviteResult(
            invite_id=invite_id, email=email, sent=False, error="link_generation_failed"
        )

    try:
        await send_email(
            template="beta_invite",
            to_email=email,
            variables={"signup_url": link},
            idempotency_key=f"email:beta_invite:{invite_id}",
            supabase=supabase,
        )
    except Exception as err:  # noqa: BLE001
        await _stamp_failed(supabase, invite_id=invite_id, message=str(err))
        return InviteResult(invite_id=invite_id, email=email, sent=False, error=str(err))

    await _stamp_sent(supabase, invite_id=invite_id)
    return InviteResult(invite_id=invite_id, email=email, sent=True)


async def send_pending_invites(
    *, limit: int = 25, supabase: AsyncClient | None = None
) -> dict[str, int]:
    """Drain up to `limit` queued invites. Each tick processes them
    sequentially because Supabase admin's generate_link is rate-limited
    server-side; parallelism here would just multiply 429s.
    """

    sb = supabase or await get_supabase()
    settings = get_settings()
    redirect_to = f"{str(settings.app_url).rstrip('/')}/onboarding"

    queued = await _list_unsent(sb, limit=limit)
    sent = 0
    failed = 0
    for invite in queued:
        result = await _send_one(sb, invite=invite, redirect_to=redirect_to)
        if result.sent:
            sent += 1
        else:
            failed += 1
    return {"sent": sent, "failed": failed, "queued": len(queued)}
