import type { LocalisedContent } from "../types";

const en = `# Terms of Service

These Terms of Service ("Terms") govern your access to and use of Quarrel AI's website, mobile applications, and related services (the "Service"). By creating an account or using the Service you agree to be bound by these Terms.

If you do not agree, do not use the Service.

## 1. The Service

Quarrel is an AI companion designed to disagree with you, push back on your reasoning, and surface contradictions over time. It produces text in response to your prompts. Outputs are generated by large language models and are **not** professional advice — they are not medical, legal, financial, mental-health, or relationship counselling. Do not use the Service as a substitute for help from a qualified professional. If you are in crisis, contact your local emergency services or one of the hotlines listed at \`/settings/safety\`.

## 2. Eligibility

You must be at least 16 years old to use the Service. Users between 16 and 17 must use only the features available to that age group (couples mode, wagers, the Roast Feed, and the persona marketplace are disabled). You must provide accurate registration information and keep it current.

You are responsible for safeguarding your account credentials. Notify us at **security@quarrel.ai** if you suspect unauthorised access.

## 3. Subscriptions, billing, and refunds

Quarrel offers a free tier plus paid Pro and Max tiers, billed monthly or annually through our merchant of record, Polar Software, Inc. ("Polar"). By starting a paid subscription you authorise Polar to charge your payment method on a recurring basis until you cancel.

- **Price changes**: we may change prices for renewal periods with at least 30 days' notice; cancel before the renewal date if you do not wish to pay the new price.
- **Refunds**: paid subscriptions are refundable within 14 days of the first payment for each billing period, provided you have not exceeded the free-tier usage equivalents during that window. After 14 days, paid subscriptions are non-refundable except where required by law.
- **Failed payments**: if a renewal payment fails we may suspend paid features after a 7-day grace period; your data is retained.
- **Cancellation**: you can cancel at any time from \`/settings/billing\`. Cancellation stops the next renewal; you retain access for the period already paid.

## 4. Wagers and anti-charity donations

The Service offers an optional commitment feature ("Wagers") that lets you stake a payment against a goal. If you fail the goal as judged under §9.5.5 of our published product reference, the staked amount is donated to a charity that you have selected from a list of "ideologically opposite" organisations.

By creating a Wager you acknowledge that:
- The donation is **real and irreversible**. We do not return the staked funds after a failure outcome.
- You must explicitly type the charity name to confirm — there is no one-click path to losing the stake.
- We are not affiliated with any charity in the list. Their views are theirs, not ours.
- Wagers are governed by the same refund window as subscriptions only until the start date you set; after the Wager becomes "active" the stake is committed.

## 5. Acceptable use

You agree not to use the Service in ways prohibited by our [Acceptable Use Policy](/legal/acceptable-use/en). Violations may result in content removal, feature restriction, or account termination. Serious violations (CSAM, real-person impersonation for harassment, fraud) are reported to the appropriate authorities.

## 6. Your content; our content

You retain ownership of the content you submit ("User Content"). You grant Quarrel a worldwide, royalty-free, non-exclusive licence to host, process, and transmit your User Content for the purpose of operating the Service. This licence ends when you delete the content, except for backups and audit logs as described in our [Privacy Policy](/legal/privacy/en).

Model outputs that you cause to be generated through the Service are yours to use, subject to the rights of any third parties whose works may have informed the model's training data. We make no claim of authorship over model outputs.

The Service itself — including the personas in our library, the brand, the codebase we have not open-sourced, and the public website copy — remains owned by Quarrel.

## 7. AI outputs

Model outputs are probabilistic and may be factually wrong, contradictory across sessions, or culturally insensitive. We work to reduce these failures but we do not warrant that outputs are accurate, fit for any purpose, or free of bias. You are responsible for evaluating model outputs before acting on them. See our [AI Disclosure](/legal/ai-disclosure/en) for the limitations we have catalogued.

## 8. Third-party services

The Service depends on third-party providers identified in our Privacy Policy (Supabase, OpenAI, Anthropic, Polar, Resend, Sentry, DigitalOcean, Cloudflare). Their availability, terms, and pricing are outside our control. We disclaim liability for outages or changes attributable to those providers.

## 9. Disclaimer

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. We do not warrant that the Service will be uninterrupted, secure, or error-free, or that any output will meet your expectations.

## 10. Limitation of liability

TO THE EXTENT PERMITTED BY APPLICABLE LAW, QUARREL'S TOTAL LIABILITY ARISING OUT OF OR RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) AMOUNTS YOU PAID US IN THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY, OR (B) USD 100. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.

Some jurisdictions do not allow these limitations; in those jurisdictions our liability is limited to the maximum extent permitted by law.

## 11. Indemnification

You agree to indemnify and hold Quarrel harmless from claims arising out of (a) your User Content, (b) your use of the Service in violation of these Terms, or (c) your violation of any law or third-party right. This does not apply to claims caused by our own negligence or wilful misconduct.

## 12. Termination

You may stop using the Service at any time and delete your account from \`/settings/data\`. We may suspend or terminate your account if you violate these Terms, if required by law, or if continuing the relationship would expose us or other users to unacceptable risk. We will provide notice and a chance to cure where reasonable.

## 13. Governing law and disputes

These Terms are governed by the laws of Bangladesh, without regard to conflict-of-law principles. Disputes will be resolved by binding arbitration seated in Dhaka, in English, under the rules of the Bangladesh International Arbitration Centre, except that either party may seek injunctive relief in any competent court for urgent intellectual-property or confidentiality issues. Consumers resident in the European Union may instead choose the courts of their habitual residence.

## 14. Changes

We may amend these Terms by posting a revised version. Material changes will be announced at least 30 days in advance by email. Continued use after the effective date constitutes acceptance.

## 15. Contact

Questions about these Terms: **legal@quarrel.ai**.
`;

export const terms: LocalisedContent = {
  en: {
    title: "Terms of Service",
    lastUpdated: "2026-05-21",
    summary:
      "The rules of using Quarrel AI: subscriptions, wagers, your content, our disclaimers, and how disputes are resolved.",
    markdown: en,
  },
  bn: null,
  hi: null,
  es: null,
  pt: null,
  ar: null,
};
